CREATE TABLE board
(
    id            INT(16) AUTO_INCREMENT PRIMARY KEY,
    category_id   INT(16) NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP
);
